export type FontType =
  | 'ant-design'
  | 'entypo'
  | 'evil-icons'
  | 'feather'
  | 'font-awesome'
  | 'font-awesome-5'
  | 'fontisto'
  | 'foundation'
  | 'ionicons'
  | 'material-icons'
  | 'material-community-icons'
  | 'octicons'
  | 'zocial'
  | 'simple-line-icons'
// | string // TODO
